.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. popbit_qt test_popbit_qt
clean: FORCE
	$(MAKE) -C .. popbit_qt_clean test_popbit_qt_clean
check: FORCE
	$(MAKE) -C .. test_popbit_qt_check
popbit-qt popbit-qt.exe: FORCE
	 $(MAKE) -C .. popbit_qt
